project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hand-on_Ex/Hand-on_Ex01/Hands-on Exercise 1.html"
        - text: "Hands-on Exercise 2"
          href: "Hand-on_Ex/Hand-on_Ex02/Hands-on Exercise 2.html"
        
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class Exercise 1.html"
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home Exercise 1.html"
    right:
      - href: index.qmd
        text: home
      - about.qmd
        
     
format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

